package appliance

type StorageArray interface {
	// CreateUsers creates local users on the array.
	// It is advised to create one user at a time unless client consuming this API
	// keeps track of successful creation of each user input.
	// If user exists already, it recreates it. This is to handle redeployment
	// There is no way to retrieve API token for a user without login as that user
	// One can retrieve his own API token, not others even if it has got admin role
	CreateUsers([]User) ([]User, error)
	// GetUsers gets a list of all the current users fro mthe stroage array.
	GetUsers() ([]User, error)
	// DeleteUser deletes the given user.  Deleting a user that doesn't exist returns success
	DeleteUser(username string) error

	// ChangeUserPassword Change the password of a user. The newPassword cannot be empty.
	ChangeUserPassword(userName string, password string, newPassword string) error
}

type User struct {
	Name string

	// Generated by Pure client
	Password string

	// Allowed values: readonly, storage_admin, and array_admin.
	// ops_admin not supported yet
	Role string
	// Provided by the Pure client.
	ApiToken string
}
